const express = require("express");
const router = express.Router();
const campaignController = require("../controllers/campaignController");
const messageController = require("../controllers/messageController");
router.post("/campaigns", campaignController.createCampaign);
router.get("/campaigns", campaignController.getCampaigns);
router.get("/messages/next", messageController.getNextJob);
router.put("/messages/:id/status", messageController.updateStatus);
router.get("/bot/instances", messageController.getBotInstancesForSupervisor);
module.exports = router;
